import {
  Code,
  History,
  Palette,
  Brain,
  Camera,
  Dumbbell,
  Music,
  Globe,
  ChefHat,
  Leaf,
  FlaskConical,
  Calculator,
  BookOpen,
  Briefcase,
  Laptop,
  Compass,
  Star,
  MapPin,
  TrendingUp,
  Heart,
  Gavel,
  Wrench,
  MessageSquare,
  User,
  Church,
  Users,
  Activity,
  Building,
} from "lucide-react-native"

export const allCategories = [
  { id: "programming", title: "Programming", icon: Code, color: "#FF6B6B" },
  { id: "history", title: "History", icon: History, color: "#4ECDC4" },
  { id: "art", title: "Art & Design", icon: Palette, color: "#9D50BB" },
  { id: "psychology", title: "Psychology", icon: Brain, color: "#45B7D1" },
  { id: "music", title: "Music", icon: Music, color: "#96C93D" },
  { id: "languages", title: "Languages", icon: Globe, color: "#FF9A8B" },
  { id: "photography", title: "Photography", icon: Camera, color: "#FF85A1" },
  { id: "fitness", title: "Fitness", icon: Dumbbell, color: "#45B7AF" },
  { id: "cooking", title: "Cooking", icon: ChefHat, color: "#FFA07A" },
  { id: "nature", title: "Nature", icon: Leaf, color: "#98FB98" },
  { id: "science", title: "Science", icon: FlaskConical, color: "#87CEEB" },
  {
    id: "mathematics",
    title: "Mathematics",
    icon: Calculator,
    color: "#FFD700",
  },
  { id: "literature", title: "Literature", icon: BookOpen, color: "#FFB6C1" },
  { id: "business", title: "Business", icon: Briefcase, color: "#20B2AA" },
  { id: "technology", title: "Technology", icon: Laptop, color: "#7B68EE" },
  { id: "philosophy", title: "Philosophy", icon: Compass, color: "#FF8C00" },
  { id: "astronomy", title: "Astronomy", icon: Star, color: "#FFA500" },
  { id: "geography", title: "Geography", icon: MapPin, color: "#40E0D0" },
  { id: "economics", title: "Economics", icon: TrendingUp, color: "#32CD32" },
  { id: "health", title: "Health", icon: Heart, color: "#FF69B4" },
  {
    id: "law-governance",
    title: "Law & Government",
    icon: Gavel,
    color: "#8A2BE2",
  },
  { id: "engineering", title: "Engineering", icon: Wrench, color: "#4682B4" },
  {
    id: "media-communication",
    title: "Media & Communication",
    icon: MessageSquare,
    color: "#D2691E",
  },
  {
    id: "personal-development",
    title: "Personal Development",
    icon: User,
    color: "#800000",
  },
  {
    id: "religious-studies",
    title: "Religious Studies",
    icon: Church,
    color: "#B22222",
  },
  {
    id: "cultural-studies",
    title: "Cultural Studies",
    icon: Users,
    color: "#DA70D6",
  },
  {
    id: "sports-recreation",
    title: "Sports & Recreation",
    icon: Activity,
    color: "#1E90FF",
  },
  {
    id: "architecture",
    title: "Architecture",
    icon: Building,
    color: "#708090",
  },
]
